version: '3'
services:
  nginx: 
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  #The app instances (same image, different volumes with configs)
  app1:
    build: ./app
    image: flask-app
    container_name: app1
    volumes:
      - ./app-data-1:/app-data #Contains name=app1 and connection to app2
  app2:
    build: ./app
    image: flask-app
    container_name: app2
    volumes:
      - ./app-data-2:/app-data #Contains name=app2 and connection to app1
